version: 2

sources:
  - name: raw
    schema: foodwaste  # Où se situe la table dans BQ
    description: Projet sur le gaspillage alimentaire batch 2006
    tables:
      - name: CO2_emissions  # Alias table BQ
        identifier: "Agrybalise - CO2 emissions"  # Nom exact de la table
        description: Données sur les émissions de CO2 liées à la production alimentaire
        tags: ["raw"]
        columns:
          - name: food_product
            description: Produit alimentaire concerné
          - name: land_use_change
            description: Impact du changement d'affectation des terres sur les émissions
          - name: animal_Feed
            description: Emissions liées à l'alimentation animale
          - name: farm
            description: Emissions générées au niveau de la ferme
          - name: processing
            description: Emissions issues du traitement et de la transformation des aliments
          - name: transport
            description: Emissions dues au transport des produits alimentaires
          - name: packging
            description: Emissions liées à l'emballage des produits
          - name: retail
            description: Emissions générées lors de la distribution et la vente au détail
          - name: total_emissions
            description: Total des émissions de CO2 générées
          - name: eutrophying_emissions_per_1000kcal__gpo___eq_per_1000kcal_
            description: Emissions eutrophisantes par 1000 kcal (grammes PO₄-eq)
          - name: eutrophying_emissions_per_kilogram__gpo___eq_per_kilogram_ 
            description: Emissions eutrophisantes par kilogramme (grammes PO₄-eq)
          - name: eutrophying_emissions_per_100g_protein__gpo___eq_per_100_grams_protein_ 
            description:  Emissions eutrophisantes par 100 g de protéines (grammes PO₄-eq)
          - name: freshwater_withdrawals_per_1000kcal__liters_per_1000kcal_
            description:  Prélèvements d'eau douce par 1000 kcal (litres)
          - name: freshwater_withdrawals_per_100g_protein__liters_per_100g_protein_ 
            description: Prélèvements d'eau douce par 100 g de protéines (litres)
          - name: freshwater_withdrawals_per_kilogram__liters_per_kilogram_
            description:  Prélèvements d'eau douce par kilogramme (litres)
          - name: greenhouse_gas_emissions_per_1000kcal__kgco___eq_per_1000kcal_ 
            description: Emissions de gaz à effet de serre par 1000 kcal (kg CO₂-eq)
          - name: greenhouse_gas_emissions_per_100g_protein__kgco___eq_per_100g_protein_
            description: Emissions de gaz à effet de serre par 100 g de protéines (kg CO₂-eq)
          - name: land_use_per_1000kcal__m___per_1000kcal_
            description: Utilisation des terres par 1000 kcal (m²)
          - name: land_use_per_kilogram__m___per_kilogram_
            description: Utilisation des terres par kilogramme (m²)
          - name: land_use_per_100g_protein__m___per_100g_protein_
            description: Utilisation des terres par 100 g de protéines (m²)
          - name: scarcity_weighted_water_use_per_kilogram__liters_per_kilogram_
            description: Utilisation de l'eau pondérée par la rareté par kilogramme (litres)
          - name: scarcity_weighted_water_use_per_100g_protein__liters_per_100g_protein_
            description:  Utilisation de l'eau pondérée par la rareté par 100 g de protéines (litres)
          - name: scarcity_weighted_water_use_per_1000kcal__liters_per_1000_kilocalories_
            description: Utilisation de l'eau pondérée par la rareté par 1000 kcal (litres)
          - name: category
            description: Catégorie du produit alimentaire
          - name: CO2_cat_id
            description: id des produits
          - name: animal_vegetal
            description: Classification du produit (animale ou végétale)

                

      - name: new_waste_table  # Alias table BQ
        identifier: New_Waste # Nom exact de la table
        description: Données sur le gaspillage alimentaire
        tags: ["raw"]
        columns:
          - name:  m49_code
            description: Code de classification des pays selon l'ONU
          - name: country
            description: Nom du pays concerné par les pertes alimentaires
          - name: cpc_code
            description: Code de classification des produits selon la norme CPC
          - name: commodity
            description: Type de produit alimentaire analysé 
          - name: year
            description: Année de mesure des pertes alimentaires
          - name: loss_percentage
            description: Pourcentage de perte alimentaire par produit et pays
          - name: activity
            description: Type activité liée aux pertes 
          - name: food_supply_stage
            description: Phase de la chaîne approvisionnement alimentaire où la perte se produit 
          - name: cause_of_loss
            description: Cause identifiée du gaspillage alimentaire 
          - name: method_data_collection
            description: Méthode de collecte des données 
          - name: reference
            description: Référence ou source utilisée pour la collecte des données
          - name:  notes
            description: Remarques supplémentaires sur la fiabilité ou la précision des données



      - name: production  # Alias table BQ
        identifier: "New_production"  # Nom exact de la table
        description: Données sur la production agricole mondiale
        tags: ["raw"]
        columns:
          - name: domain_code
            description: Code du domaine FAO pour la classification des données
          - name: domain
            description:  Nom du domaine
          - name: area Code
            description: Code M49 attribué au pays ou à la région selon l'ONU
          - name: area
            description: Nom du pays ou de la région
          - name: element_code
            description: Code de l'élément décrivant la mesure de production
          - name: element
            description: Type de donnée mesurée
          - name: item Code _CPC_
            description: Code CPC de classification des produits alimentaires
          - name: item
            description:  Nom du produit alimentaire
          - name: year
            description:  Année de collecte des données
          - name: unit
            description: Unité de mesure utilisée
          - name: value
            description: Valeur correspondant à la quantité produite
          - name: flag
            description: indicateur utilisé par la FAO pour qualifier la source, la fiabilité ou le mode d’obtention des données
          - name: flag_description
            description: Description du code drapeau
          - name: sub_region_name
            description: sous-régions et leurs continents
          - name: region_name
            description: continents
          - name: CO2_Id
            description: numéro CO2 ID




      - name: Loss_mediane  # Alias table BQ
        identifier: "Loss_median"  # Nom exact de la table
        description: Mediane du % de perte par produit
        tags: ["raw"]
        columns:
          - name: commodity
            description: Type de produit alimentaire de la table wast
          - name: cpc_code
            description: Code de classification des produits selon la norme CPC de la table wast
          - name: loss_percentage
            description:  Pourcentage de perte alimentaire par produit et pays de la table waste




      - name: merge_median_production 
        description: Fusion des données de production et Loss_mediane pour calculer la valeur des pertes alimentaire en fonction du pourcentage de perte et de la quantité produite
        tags: ["intermediate"]
        columns:
          - name: domain_code
            description: Code du domaine FAO pour la classification des données
          - name: domain
            description:  Nom du domaine
          - name: area Code
            description: Code M49 attribué au pays ou à la région selon l'ONU
          - name: area
            description: Nom du pays ou de la région
          - name: element_code
            description: Code de l'élément décrivant la mesure de production
          - name: element
            description: Type de donnée mesurée
          - name: item Code _CPC_
            description: Code CPC de classification des produits alimentaires
          - name: item
            description:  Nom du produit alimentaire
          - name: year
            description:  Année de collecte des données
          - name: unit
            description: Unité de mesure utilisée
          - name: value
            description: Valeur correspondant à la quantité produite
          - name: flag
            description: indicateur utilisé par la FAO pour qualifier la source, la fiabilité ou le mode obtention des données
          - name: flag_description
            description: Description du code drapeau
          - name: sub_region_name
            description: sous-régions et leurs continents
          - name: region_name
            description: continents
          - name: CO2_Id
            description: numéro CO2 ID
          - name: loss_percentage
            description: Pourcentage de perte alimentaire par produit et pays de la table waste
          - name: loss_value
            description: Valeur totale de la perte alimentaire calculée


      


      - name: merge_CO2_production  
        description: Fusion des données de production médiane et des émissions de CO2 liées aux produits alimentaires
        tags: ["intermediate"]
        columns:
          - name: domain_code
            description: Code du domaine FAO pour la classification des données
          - name: domain
            description:  Nom du domaine
          - name: area Code
            description: Code M49 attribué au pays ou à la région selon l'ONU
          - name: area
            description: Nom du pays ou de la région
          - name: element_code
            description: Code de l'élément décrivant la mesure de production
          - name: element
            description: Type de donnée mesurée
          - name: item Code _CPC_
            description: Code CPC de classification des produits alimentaires
          - name: item
            description:  Nom du produit alimentaire
          - name: year
            description:  Année de collecte des données
          - name: unit
            description: Unité de mesure utilisée
          - name: value
            description: Valeur correspondant à la quantité produite
          - name: flag
            description: indicateur utilisé par la FAO pour qualifier la source, la fiabilité ou le mode d’obtention des données
          - name: flag_description
            description: Description du code drapeau
          - name: sub_region_name
            description: sous-régions et leurs continents
          - name: region_name
            description: continents
          - name: CO2_Id
            description: numéro CO2 ID
          - name: loss_percentage
            description: Pourcentage de perte alimentaire par produit et pays de la table waste
          - name: loss_value
            description: Valeur totale de la perte alimentaire calculée
          - name: total_emissions
            description: Total des émissions de CO2 générées
          - name: food_product
            description: Produit alimentaire concerné
          - name: category
            description: Catégorie du produit alimentaire
          - name: animal_vegetal
            description: Classification du produit (animale ou végétale)





      - name: FAO_prod_loss_Final
        description: calcul des pertes alimentaires à partir des données de production médiane
        tags: ["mart"]
        columns:
          - name: year
            description:  Année de collecte des données
          - name: region_name
            description: continents
          - name: sub_region_name
            description: sous-régions et leurs continents
          - name: country 
            description:  Nom du pays
          - name: item
            description:  Nom du produit alimentaire
          - name: value
            description: Valeur correspondant à la quantité produite
          - name: loss_percentage
            description: Pourcentage de perte alimentaire par produit et pays de la table waste
          - name: loss_value
            description: Valeur totale de la perte alimentaire calculée
          
          
          
      - name: FAO_CO2_Final
        description: Calcul de limpact environnemental des pertes alimentaires en fonction des émissions de CO2 générées
        tags: ["mart"]
        columns:
          - name: year
            description:  Année de collecte des données
          - name: region_name
            description: Continents
          - name: sub_region_name
            description: Sous-régions et leurs continents
          - name: country
            description: Nom du pays
          - name: origin_type
            description: Classification du produit (animale ou végétale) 
          - name: food_group
            description: Catégorie du produit alimentaire
          - name: item_group
            description: Produit alimentaire concerné
          - name: item
            description:  Nom du produit alimentaire
          - name: value_tonnes
            description: Valeur correspondant à la quantité produite
          - name: loss_percentage
            description: Pourcentage de perte alimentaire par produit et pays de la table waste
          - name: loss_value_tonnes
            description: Valeur totale de la perte alimentaire calculée
          - name: total_emissions
            description: Total des émissions de CO2 générées
          - name: wasted_CO2_tonnes
            description: Quantité estimée de CO2 gaspillée à cause des pertes alimentaires
          - name: producted_CO2_tonnes
            description: Quantité totale de CO2 générée par la production alimentaire 





          
          
          
   
          
          
          
          




          
          
   
        
       