version: 2

sources:
  - name: raw
    schema: foodwaste # où se situe la table dans BQ
    description: projet sur le gaspillage alimentaire batch 2006
    tables:
      - name: CO2_emissions #alias table BQ
        identifier: Agrybalise - CO2 emissions # nom exact de la table
        description: Une qui fait le lien entre chaque type de produit et l’émission de CO2
      - name: Food_Waste_table #alias table BQ
<<<<<<< HEAD
        identifier: FAO - Food Waste # nom exact de la table
        description: Une table qui fait le lien avec les quantités de produits qui sont produits et jetés
=======
        identifier: Waste3 # nom exact de la table
        description: bla
>>>>>>> 30e9c95b57522f37888890cc94784bc1e58340ec
      - name: Food_productions #alias table BQ
        identifier: FAO - Food productions # nom exact de la table
        description: Une table produits par chaque pays
         